import type { Metadata } from "next";
import { Check, Clock3 } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import PrintReceiptButton from "@/components/PrintReceiptButton";
import { getSessionUser } from "@/lib/auth";
import { getDatabase } from "@/lib/db";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Payout statement | HarvestNearU", robots: { index: false, follow: false } };
type Props={params:Promise<{id:string}>}; type Row=Record<string,unknown>;
const money=(value:unknown)=>new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:0}).format(Number(value)/100);
const date=(value:unknown)=>value?new Intl.DateTimeFormat("en-NG",{dateStyle:"medium",timeStyle:"short",timeZone:"Africa/Lagos"}).format(new Date(String(value))):"Not recorded";
const label=(value:unknown)=>String(value||"").replaceAll("_"," ").replace(/\b\w/g,(letter)=>letter.toUpperCase());

export default async function PayoutReceipt({params}:Props){const user=await getSessionUser();if(!user||user.role!=="farmer")notFound();const {id}=await params;const sql=getDatabase();const rows=await sql`SELECT request.*,farm.name AS farm_name,account.bank_name,account.account_name,account.account_last4 FROM payout_requests request JOIN farms farm ON farm.id=request.farm_id LEFT JOIN farmer_payout_accounts account ON account.farm_id=farm.id AND account.is_default WHERE request.id=${id} AND farm.owner_id=${user.id} LIMIT 1`;if(!rows[0])notFound();const payout=rows[0] as Row;const orders=await sql`SELECT orders.order_number,farm_order.subtotal_kobo,farm_order.platform_fee_kobo,farm_order.farmer_net_kobo FROM payout_request_orders link JOIN farm_orders farm_order ON farm_order.id=link.farm_order_id JOIN orders ON orders.id=farm_order.order_id WHERE link.payout_request_id=${id} ORDER BY orders.placed_at`;
return <main className="receipt-page"><div className="receipt-toolbar"><Link href="/farmer">Back to farmer workspace</Link><PrintReceiptButton/></div><article className="receipt-sheet"><header><Image src="/brand/harvestnearu-opaque-seal-se2-lockup.png" width={210} height={52} alt="HarvestNearU" priority/><div><span className="receipt-paid">{String(payout.status)==="paid"?<><Check size={14}/> Paid</>:<><Clock3 size={14}/> {label(payout.status)}</>}</span><h1>Payout statement</h1><p>Reference {String(payout.id).slice(0,8).toUpperCase()}</p></div></header><section className="receipt-parties"><div><small>PAYABLE TO</small><strong>{String(payout.farm_name)}</strong><span>{payout.account_name?String(payout.account_name):"Payout account not configured"}</span>{Boolean(payout.account_last4)&&<span>{String(payout.bank_name||"Bank account")} · ending {String(payout.account_last4)}</span>}</div><div><small>STATEMENT DETAILS</small><dl><dt>Requested</dt><dd>{date(payout.requested_at)}</dd><dt>Reviewed</dt><dd>{date(payout.reviewed_at)}</dd><dt>Paid</dt><dd>{date(payout.paid_at)}</dd><dt>Status</dt><dd>{label(payout.status)}</dd></dl></div></section><table><thead><tr><th>Included order</th><th>Gross sale</th><th>Platform fee</th><th>Net payout</th></tr></thead><tbody>{(orders as Row[]).map((order)=><tr key={String(order.order_number)}><td><strong>Order #{String(order.order_number)}</strong></td><td>{money(order.subtotal_kobo)}</td><td>-{money(order.platform_fee_kobo)}</td><td>{money(order.farmer_net_kobo)}</td></tr>)}</tbody></table><section className="receipt-totals"><span><em>Gross sales</em><strong>{money(payout.gross_amount_kobo)}</strong></span><span><em>Platform fee</em><strong>-{money(payout.platform_fee_kobo)}</strong></span><span className="receipt-total"><em>Net payout</em><strong>{money(payout.net_amount_kobo)}</strong></span></section>{Boolean(payout.review_note)&&<section className="receipt-fulfilment"><Clock3 size={19}/><div><small>ADMINISTRATOR NOTE</small><strong>{String(payout.review_note)}</strong></div></section>}<footer><p>HarvestNearU farmer payout statement.</p><span>HarvestNearU | harvestnearu.com | hello@harvestnearu.com</span></footer></article></main>}
